version: "3.8"

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - APP_MODEL_PATH=/app/treino_modelo/artifacts/model.onnx
      - APP_MODEL_VERSION=tfidf-rf-v1.0-onnx
    restart: unless-stopped
    depends_on:
      - prometheus
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ../docker/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ../docker/grafana/provisioning:/etc/grafana/provisioning:ro
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_ID=0
